# Generated by Django 5.2.4 on 2025-07-25 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อ-นามสกุล')),
                ('email', models.EmailField(max_length=254, verbose_name='อีเมล')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='หัวข้อ')),
                ('message', models.TextField(verbose_name='ข้อความ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่ส่ง')),
                ('is_read', models.BooleanField(default=False, verbose_name='อ่านแล้ว')),
            ],
            options={
                'verbose_name': 'ข้อความติดต่อ',
                'verbose_name_plural': 'ข้อความติดต่อ',
                'ordering': ['-created_at'],
            },
        ),
    ]
